name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    env:
      COMMITS: ${{ toJson(github.event.commits) }}
      COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
    steps:
      - uses: actions/checkout@v6
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits general
        run: echo "$COMMITS"
      - name: head commit
        run: echo "Head commit ${{github.head_commit}}"
      - name: first commit id
        run: echo "Commit id ${{github.event.commits[0].id}}"
      - name: first commit message
        run: echo "Commit message ${{github.event.commits[0].message}}"
      - name: commit messages
        run: echo "$COMMIT_MESSAGES"
      - name: evaluating commit messages
        if: ${{contains(join(env.COMMIT_MESSAGES),'try')}}
        run: echo "COMMIT_MESSAGES contains try"
      - name: getting job status
        run: echo "Job status ${{job.status}}"
      - name: Notify discord if deployment success
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          notimestamp: true
          color: #90EE90
          content: ":white_check_mark: **Deployment Successfull!** A new version deployed to production"
          title: "Deployment details"
          description: |
            **Commit:** ${{ github.event.commits[0].id }}
            **Message:** ${{ github.event.commits[0].message }}
            **Author:** ${{ github.event.commits[0].author.name }}
